### PR TITLE
Made modifications/improvements to the help text: `helpLinguists`.

### PR DESCRIPTION
**Pull request by jrwdunham**

### CODE REVIEW

**Comment by cesine** [comment]
thanks @jrwdunham ! are you sure you didn't want the change the default "help" texts too? the spreadsheet will show the defaults... not the linguist texts. I agree these should be in a help icon instead of hover texts, the spreadsheet app has no help icons probably to reduce visual clutter. 

some of the are still too technical, like the gloss one says its a gloss, but there are defintely users who will say that "gloss" is a technival word. maybe it could say something like word for word translation?

this also breaks the build, do you dare to fix the testes at the same time (click on the travis failed above to see what it broke). it would be great if you could learn how to build and run the tests.

**Comment by jrwdunham** [comment]
Ok, I made the `help` values the same as the `helpLinguists` values, more or less across the board.

I also gave more of an explanation of what "gloss" means in that field's help text. However, I think one of the other issues that the stakeholders had with these help texts was that they were too pedantic/ assumed too little knowledge on the part of users...

I fixed tests/datum/DatumFields-spec.js so that the tests now pass and the build should too.

Also, I don't know if you read that far down into the file I sent around about these help texts, but the help text for "confidentiality" does not accord with the array of options in `json.choices` for that field. The value of `json.choices` for this field is `["generalize", "team", "anonymous", “public”]`. This is a mismatch with the value listed in the `helpLinguists` value: “hidden” is mentioned there but not in `json.choices` while “generalize” is mentioned here but not there. Maybe you (@cesine) want to fix this since you understand this better.

**Comment by cesine** [comment]
@jrwdunham i did read the entire doc, and i agreed with you that it didnt accord but i think that the simple solution is to make the choices and help text match (ie i think this means add hidden to the choices and add generalize to the help text) i can maybe do it. no one uses the confidentiality of speakers since we have no interface in the app to create speakers :) only  the psycholing dash has an interface to view speakers/participants so i dont mind if this update doesnt get fixed right away, 

it would be easiest/awesome for you to just fix it since you saw it ...

**Comment by jrwdunham** [comment]
Ok, I'll make an issue of this and do that, but can you merge this request we can deploy the new release?

**Comment by cesine** [comment]
I cant merge it yet, it has conflicts so i have to resolve those first, or you could do it by pulling from upstream and resolving conflicts and pushing back to your origin, if you want practice :)

**Pull request merged**
